# Generated by Django 5.2.7 on 2025-10-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
