# Generated by Django 5.2.7 on 2025-10-22 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0007_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
