# Generated by Django 5.2.7 on 2025-10-26 10:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0010_reviewlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
