# Generated by Django 5.2.7 on 2025-10-26 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0011_reviewimage_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gasoline', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('diesel', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('kerosene', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('region', models.CharField(default='National Average', max_length=100)),
                ('source', models.CharField(default='DOE Philippines', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Fuel Prices',
                'get_latest_by': 'last_updated',
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_images', to='projectapp.post')),
            ],
        ),
    ]
