# Generated by Django 5.2.7 on 2025-10-26 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0012_fuelprice_postimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='uploaded_at',
            new_name='created_at',
        ),
    ]
